<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="NTPL-IT-MAC-LAP0099" failures="5" tests="12" name="Growth API Sanity Tests" time="58.526" errors="0" timestamp="2025-07-21T12:03:29 IST">
  <testcase classname="com.coindcx.trade.earn.EarnFlowTest" name="cancelPastOrders" time="6.291">
    <failure type="java.lang.RuntimeException" message="Error occurred while executing update: &amp;quot;coindcx.db.pool&amp;quot; - Connection is not available, request timed out after 5008ms (total=0, active=0, idle=0, waiting=0)">
      <![CDATA[java.lang.RuntimeException: Error occurred while executing update: "coindcx.db.pool" - Connection is not available, request timed out after 5008ms (total=0, active=0, idle=0, waiting=0)
at MasterDatabase.DbBase.executeUpdate(DbBase.java:93)
at database.tables.earn.FundingOrders.updateCreateAtInFundingOrdersTable(FundingOrders.java:50)
at com.coindcx.trade.earn.EarnFlowTest.cancelPastOrders(EarnFlowTest.java:385)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.sql.SQLTransientConnectionException: "coindcx.db.pool" - Connection is not available, request timed out after 5008ms (total=0, active=0, idle=0, waiting=0)
at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:710)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:189)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
at MasterDatabase.DBConnectionManager.getConnection(DBConnectionManager.java:77)
at MasterDatabase.DbBase.executeUpdate(DbBase.java:82)
... 29 more
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- cancelPastOrders -->
  <testcase classname="com.coindcx.trade.earn.EarnFlowTest" name="cancelPastOrders" time="6.201">
    <failure type="java.lang.RuntimeException" message="Error occurred while executing update: &amp;quot;coindcx.db.pool&amp;quot; - Connection is not available, request timed out after 5010ms (total=0, active=0, idle=0, waiting=0)">
      <![CDATA[java.lang.RuntimeException: Error occurred while executing update: "coindcx.db.pool" - Connection is not available, request timed out after 5010ms (total=0, active=0, idle=0, waiting=0)
at MasterDatabase.DbBase.executeUpdate(DbBase.java:93)
at database.tables.earn.FundingOrders.updateCreateAtInFundingOrdersTable(FundingOrders.java:50)
at com.coindcx.trade.earn.EarnFlowTest.cancelPastOrders(EarnFlowTest.java:385)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.sql.SQLTransientConnectionException: "coindcx.db.pool" - Connection is not available, request timed out after 5010ms (total=0, active=0, idle=0, waiting=0)
at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:710)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:189)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
at MasterDatabase.DBConnectionManager.getConnection(DBConnectionManager.java:77)
at MasterDatabase.DbBase.executeUpdate(DbBase.java:82)
... 29 more
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:358)
at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
at org.postgresql.Driver.makeConnection(Driver.java:446)
at org.postgresql.Driver.connect(Driver.java:298)
at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:139)
at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:367)
at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:205)
at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:484)
at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:748)
at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
at --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)
at java.base/java.util.concurrent.FutureTask.<init>(FutureTask.java:132)
at java.base/java.util.concurrent.AbstractExecutorService.newTaskFor(AbstractExecutorService.java:113)
at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:144)
at com.zaxxer.hikari.pool.HikariPool.addBagItem(HikariPool.java:340)
at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:146)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:165)
... 33 more
Caused by: java.net.SocketTimeoutException: Connect timed out
at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
at java.base/java.net.Socket.connect(Socket.java:633)
at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
at org.postgresql.core.PGStream.<init>(PGStream.java:98)
at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:136)
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262)
... 52 more
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- cancelPastOrders -->
  <testcase classname="com.coindcx.trade.earn.EarnFlowTest" name="validateAdvancedEarnCancellationAfter90Days" time="5.722">
    <failure type="java.lang.RuntimeException" message="Error occurred while executing update: &amp;quot;coindcx.db.pool&amp;quot; - Connection is not available, request timed out after 5006ms (total=0, active=0, idle=0, waiting=0)">
      <![CDATA[java.lang.RuntimeException: Error occurred while executing update: "coindcx.db.pool" - Connection is not available, request timed out after 5006ms (total=0, active=0, idle=0, waiting=0)
at MasterDatabase.DbBase.executeUpdate(DbBase.java:93)
at database.tables.earn.FundingOrders.updateCreateAtInFundingOrdersTable(FundingOrders.java:50)
at com.coindcx.trade.earn.EarnFlowTest.validateAdvancedEarnCancellationAfter90Days(EarnFlowTest.java:302)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.sql.SQLTransientConnectionException: "coindcx.db.pool" - Connection is not available, request timed out after 5006ms (total=0, active=0, idle=0, waiting=0)
at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:710)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:189)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
at MasterDatabase.DBConnectionManager.getConnection(DBConnectionManager.java:77)
at MasterDatabase.DbBase.executeUpdate(DbBase.java:82)
... 29 more
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:358)
at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
at org.postgresql.Driver.makeConnection(Driver.java:446)
at org.postgresql.Driver.connect(Driver.java:298)
at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:139)
at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:367)
at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:205)
at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:484)
at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:748)
at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
at --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)
at java.base/java.util.concurrent.FutureTask.<init>(FutureTask.java:132)
at java.base/java.util.concurrent.AbstractExecutorService.newTaskFor(AbstractExecutorService.java:113)
at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:144)
at com.zaxxer.hikari.pool.HikariPool.addBagItem(HikariPool.java:340)
at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:146)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:165)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
at MasterDatabase.DBConnectionManager.getConnection(DBConnectionManager.java:77)
at MasterDatabase.DbBase.executeUpdate(DbBase.java:82)
at database.tables.earn.FundingOrders.updateCreateAtInFundingOrdersTable(FundingOrders.java:50)
at com.coindcx.trade.earn.EarnFlowTest.cancelPastOrders(EarnFlowTest.java:385)
... 27 more
Caused by: java.net.SocketTimeoutException: Connect timed out
at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
at java.base/java.net.Socket.connect(Socket.java:633)
at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
at org.postgresql.core.PGStream.<init>(PGStream.java:98)
at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:136)
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262)
... 52 more
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- validateAdvancedEarnCancellationAfter90Days -->
  <testcase classname="com.coindcx.trade.earn.EarnFlowTest" name="validateCancelOrderAfterSuccessfulOrderPlaced" time="15.652"/>
  <testcase classname="com.coindcx.trade.earn.EarnFlowTest" name="validateImmediateSettlementOfSimpleLendingOrder" time="5.833">
    <failure type="java.lang.RuntimeException" message="Error occurred while executing update: &amp;quot;coindcx.db.pool&amp;quot; - Connection is not available, request timed out after 5006ms (total=0, active=0, idle=0, waiting=0)">
      <![CDATA[java.lang.RuntimeException: Error occurred while executing update: "coindcx.db.pool" - Connection is not available, request timed out after 5006ms (total=0, active=0, idle=0, waiting=0)
at MasterDatabase.DbBase.executeUpdate(DbBase.java:93)
at database.tables.earn.FundingOrders.updateCreateAtInFundingOrdersTable(FundingOrders.java:50)
at com.coindcx.trade.earn.EarnFlowTest.validateImmediateSettlementOfSimpleLendingOrder(EarnFlowTest.java:256)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.sql.SQLTransientConnectionException: "coindcx.db.pool" - Connection is not available, request timed out after 5006ms (total=0, active=0, idle=0, waiting=0)
at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:710)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:189)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
at MasterDatabase.DBConnectionManager.getConnection(DBConnectionManager.java:77)
at MasterDatabase.DbBase.executeUpdate(DbBase.java:82)
... 29 more
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:358)
at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
at org.postgresql.Driver.makeConnection(Driver.java:446)
at org.postgresql.Driver.connect(Driver.java:298)
at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:139)
at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:367)
at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:205)
at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:484)
at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:748)
at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
at --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)
at java.base/java.util.concurrent.FutureTask.<init>(FutureTask.java:132)
at java.base/java.util.concurrent.AbstractExecutorService.newTaskFor(AbstractExecutorService.java:113)
at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:144)
at com.zaxxer.hikari.pool.HikariPool.addBagItem(HikariPool.java:340)
at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:146)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:165)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
at MasterDatabase.DBConnectionManager.getConnection(DBConnectionManager.java:77)
at MasterDatabase.DbBase.executeUpdate(DbBase.java:82)
at database.tables.earn.FundingOrders.updateCreateAtInFundingOrdersTable(FundingOrders.java:50)
at com.coindcx.trade.earn.EarnFlowTest.cancelPastOrders(EarnFlowTest.java:385)
... 27 more
Caused by: java.net.SocketTimeoutException: Connect timed out
at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
at java.base/java.net.Socket.connect(Socket.java:633)
at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
at org.postgresql.core.PGStream.<init>(PGStream.java:98)
at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:136)
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262)
... 52 more
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- validateImmediateSettlementOfSimpleLendingOrder -->
  <testcase classname="com.coindcx.trade.earn.EarnFlowTest" name="verifyActiveEarningsAreListedForAllTokens" time="1.768"/>
  <testcase classname="com.coindcx.trade.earn.EarnFlowTest" name="verifyActiveEarningsAreListedForAllTokens" time="1.422"/>
  <testcase classname="com.coindcx.trade.earn.EarnFlowTest" name="verifyEarnErrorMessageWhenAmountBreached" time="0.677"/>
  <testcase classname="com.coindcx.trade.earn.EarnFlowTest" name="verifyEarnErrorMessageWhenAmountBreached" time="0.503"/>
  <testcase classname="com.coindcx.trade.earn.EarnFlowTest" name="verifyEarnErrorMessageWhenAmountBreached" time="0.561"/>
  <testcase classname="com.coindcx.trade.earn.EarnFlowTest" name="verifyEarningsSection" time="6.464">
    <failure type="java.lang.RuntimeException" message="Error occurred while executing update: &amp;quot;coindcx.db.pool&amp;quot; - Connection is not available, request timed out after 5007ms (total=0, active=0, idle=0, waiting=0)">
      <![CDATA[java.lang.RuntimeException: Error occurred while executing update: "coindcx.db.pool" - Connection is not available, request timed out after 5007ms (total=0, active=0, idle=0, waiting=0)
at MasterDatabase.DbBase.executeUpdate(DbBase.java:93)
at database.tables.earn.FundingOrders.updateCreateAtInFundingOrdersTable(FundingOrders.java:50)
at com.coindcx.trade.earn.EarnFlowTest.verifyEarningsSection(EarnFlowTest.java:584)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
Caused by: java.sql.SQLTransientConnectionException: "coindcx.db.pool" - Connection is not available, request timed out after 5007ms (total=0, active=0, idle=0, waiting=0)
at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:710)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:189)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
at MasterDatabase.DBConnectionManager.getConnection(DBConnectionManager.java:77)
at MasterDatabase.DbBase.executeUpdate(DbBase.java:82)
... 29 more
Caused by: org.postgresql.util.PSQLException: The connection attempt failed.
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:358)
at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
at org.postgresql.Driver.makeConnection(Driver.java:446)
at org.postgresql.Driver.connect(Driver.java:298)
at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:139)
at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:367)
at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:205)
at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:484)
at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:748)
at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:727)
at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
at --- Async.Stack.Trace --- (captured by IntelliJ IDEA debugger)
at java.base/java.util.concurrent.FutureTask.<init>(FutureTask.java:132)
at java.base/java.util.concurrent.AbstractExecutorService.newTaskFor(AbstractExecutorService.java:113)
at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:144)
at com.zaxxer.hikari.pool.HikariPool.addBagItem(HikariPool.java:340)
at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:146)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:165)
at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147)
at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:99)
at MasterDatabase.DBConnectionManager.getConnection(DBConnectionManager.java:77)
at MasterDatabase.DbBase.executeUpdate(DbBase.java:82)
at database.tables.earn.FundingOrders.updateCreateAtInFundingOrdersTable(FundingOrders.java:50)
at com.coindcx.trade.earn.EarnFlowTest.validateImmediateSettlementOfSimpleLendingOrder(EarnFlowTest.java:256)
... 27 more
Caused by: java.net.SocketTimeoutException: Connect timed out
at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551)
at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
at java.base/java.net.Socket.connect(Socket.java:633)
at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
at org.postgresql.core.PGStream.<init>(PGStream.java:98)
at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:136)
at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:262)
... 52 more
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- verifyEarningsSection -->
  <testcase classname="com.coindcx.trade.earn.EarnFlowTest" name="verifyErrorMessageWhenAmountIsLessThanMin" time="0.573"/>
  <testcase classname="com.coindcx.trade.earn.EarnFlowTest" name="verifyPayoutDateUpdatesAfterFirstPayout" time="0.0">
    <ignored/>
  </testcase> <!-- verifyPayoutDateUpdatesAfterFirstPayout -->
</testsuite> <!-- Growth API Sanity Tests -->
